export const PUBLIC_CONFIG = {
  SOLANA_NETWORK: 'devnet',
  SOLANA_RPC_URL: 'https://api.devnet.solana.com',
  FC_PER_SOL: 100,
  TREASURY_WALLET_PUBLIC_KEY: 'YOUR_ADMIN_WALLET_PUBLIC_KEY_HERE',
  FC_TOKEN_MINT_PUBLIC_KEY: 'YOUR_FC_TOKEN_MINT_PUBLIC_KEY_HERE'
};
